### PR TITLE
Ekinzie/swagger types

### PR DESCRIPTION
**Pull request by ekinzie**

### CODE REVIEW

**Review by mbj4668 — COMMENTED** [review]
I think it is unfortunate that RFC 7951 says that (u)int64 should be encoded as strings.  Neither JSON or JSON schema or Swagger or OpenAPI restricts integers.  I am currently working on a project where we use swagger and YAML w/o this restriction.

So I don't really want to make this change as is (int64 should map to {integer, int64}, however).

An idea is to introduce a new flag, perhaps --swagger-rfc7951, or --swagger-int64-as-strings to control this.

**Comment by ekinzie** [comment]
It is unfortunate.  I think adding a flag to control this is a fine idea and I have updated the branch.

**Comment by ekinzie** [comment]
Any thoughts on this?  I know the patch has gone from a few lines to something significantly larger.

**Comment by mbj4668** [comment]
I am on vacation and will check this when I get back.

Den fre 16 juli 2021 21:40ekinzie ***@***.***> skrev:

**Comment by mbj4668** [comment]
I realized that the name I suggested was not good (I don't like having rfc numbers in options, since rfcs may get updated), so I changed the name.  Thanks for the PR!

**Pull request merged**
